[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "@imtbl/=node_modules/@imtbl/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "erc721a/=node_modules/erc721a/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
